package view;

import controller.FornecedorController;
import model.ProdutoModel;
import controller.ProdutoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FornecedorModel;
/**
 *
 * @author Cris
 */
public class ProdutoView extends javax.swing.JInternalFrame {
    
    private ArrayList<FornecedorModel> listaFornecedores;
    private int linha = -1;
    public ProdutoView() {
        initComponents();
        preencherTabela();
        inicializa();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxidProduto = new javax.swing.JTextField();
        jtxDescricao = new javax.swing.JTextField();
        jtxEstoque = new javax.swing.JTextField();
        jtxValor = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProduto = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jcbFornecedor = new javax.swing.JComboBox<>();

        jLabel1.setText("Descrição:");

        jLabel2.setText("Código:");

        jLabel3.setText("Estoque");

        jLabel4.setText("Valor:");

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jtProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Estoque", "Valor", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProduto);

        jLabel5.setText("Fornecedor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxidProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbPesquisar))
                                    .addComponent(jtxDescricao)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalvar)
                                .addGap(32, 32, 32)
                                .addComponent(jbEditar)
                                .addGap(30, 30, 30)
                                .addComponent(jbExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbFechar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addComponent(jcbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxidProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbPesquisar.setEnabled(false);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);
        jtxidProduto.setEditable(false);
        jtxDescricao.setEditable(true);
        jtxEstoque.setEditable(true);
        jtxValor.setEditable(true);
        
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        
        if((jtxDescricao.getText().isEmpty())||(jtxEstoque.getText().isEmpty())||(jtxValor.getText().isEmpty()))
            JOptionPane.showMessageDialog(this, "Digite todos os campos!"
                    , "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        else{
            String descricao = jtxDescricao.getText();
            int estoque = Integer.parseInt(jtxEstoque.getText());
            float valor  = Float.parseFloat(jtxValor.getText());
            String forn = (String) jcbFornecedor.getSelectedItem();
            int fornecedor = 0;
            for(int i=0; i< listaFornecedores.size();i++){
                if(forn.equals(listaFornecedores.get(i).getRazaoSocial())){
                    fornecedor = listaFornecedores.get(i).getIdFornecedor();
                    break;
                }
            }
            ProdutoModel produto = new ProdutoModel();
            produto.setDescricao(descricao);
            produto.setEstoque(estoque);
            produto.setValor(valor);
            produto.getFornecedor().setIdFornecedor(fornecedor);
            //CONTROLLER
            ProdutoController controller = new ProdutoController();
            if(controller.inserir(produto)){
                JOptionPane.showMessageDialog(this, "Produto Inserido com sucesso!");
                limparCampos();
                inicializa();
                preencherTabela();
            }else
                JOptionPane.showMessageDialog(this, "Erro ao inserir o produto!"
                    , "Retorno BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        ProdutoModel produto = new ProdutoModel();
        if(jtxidProduto.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Preencha o código do produto!"
                    , "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        else{
            produto.setIdproduto(Integer.parseInt(jtxidProduto.getText()));
            //CONTROLLER
            ProdutoController controller = new ProdutoController();
            produto = controller.selecionar(produto);
            //VALIDAR SE OBJETO FORNECEDOR FOI ENCONTRADO... 
            if(produto == null)
                JOptionPane.showMessageDialog(this, "Produto não encontrado!"
                    , "Retorno BD", JOptionPane.ERROR_MESSAGE);
            else{
                //PREENCHER OS CAMPOS...
                jtxDescricao.setText(produto.getDescricao());
                jtxEstoque.setText(String.valueOf(produto.getEstoque()));
                jtxValor.setText(String.valueOf(produto.getValor()));
                jcbFornecedor.setSelectedItem(produto.getFornecedor().getRazaoSocial());
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jtxidProduto.setEditable(false);
                jtxDescricao.setEditable(true);
                jtxEstoque.setEditable(true);
                jtxValor.setEditable(true);
                
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        int idproduto = Integer.parseInt(jtxidProduto.getText());
        
        if((jtxDescricao.getText().isEmpty())||(jtxEstoque.getText().isEmpty())||(jtxValor.getText().isEmpty()))
            JOptionPane.showMessageDialog(this, "Digite todos os campos!"
                    , "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        else{
            String descricao = jtxDescricao.getText();
            int estoque = Integer.parseInt(jtxEstoque.getText());
            float valor  = Float.parseFloat(jtxValor.getText());
            String forn = (String)jcbFornecedor.getSelectedItem();
            int fornecedor = 0;
            for(int i=0; i<listaFornecedores.size();i++){
                if(forn.equals(listaFornecedores.get(i).getRazaoSocial())){
                    fornecedor = listaFornecedores.get(i).getIdFornecedor();
                    break;
                }
            }
            ProdutoModel produto = new ProdutoModel();
            produto.setIdproduto(idproduto);
            produto.setDescricao(descricao);
            produto.setEstoque(estoque);
            produto.setValor(valor);
            produto.getFornecedor().setIdFornecedor(fornecedor);
            //CONTROLLER
            ProdutoController controller = new ProdutoController();
            if(controller.editar(produto)){
                JOptionPane.showMessageDialog(this, "Atualização com sucesso!");
                limparCampos();
                inicializa();
                preencherTabela();
            }else
                JOptionPane.showMessageDialog(this, "Erro ao editar produto!"
                    , "Retorno BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        ProdutoModel produto = new ProdutoModel();
        if(jtxidProduto.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Digite o código do produto!"
                    , "Retorno Tela", JOptionPane.ERROR_MESSAGE);
        else{
            produto.setIdproduto(Integer.parseInt(jtxidProduto.getText()));
            //CONTROLLER 
            ProdutoController controller = new ProdutoController();
            if(controller.excluir(produto)){
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                limparCampos();
                inicializa();
                preencherTabela();
            }else 
                JOptionPane.showMessageDialog(this, "Erro ao Excluir!"
                    , "Retorno BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutoMouseClicked
        linha = jtProduto.getSelectedRow();
        if(linha !=-1){
            jtxidProduto.setText(jtProduto.getValueAt(linha, 0).toString());
            jtxDescricao.setText(jtProduto.getValueAt(linha, 1).toString());
            jtxEstoque.setText(jtProduto.getValueAt(linha, 2).toString());
            jtxValor.setText(jtProduto.getValueAt(linha, 3).toString());
            jcbFornecedor.setSelectedItem(jtProduto.getValueAt(linha, 4).toString());
            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxidProduto.setEditable(false);
            jtxDescricao.setEditable(true);
            jtxEstoque.setEditable(true);
            jtxValor.setEditable(true);
            
            linha = -1;
        }
    }//GEN-LAST:event_jtProdutoMouseClicked

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
       dispose();
    }//GEN-LAST:event_jbFecharActionPerformed
    private void preencherTabela(){
        ProdutoController controller = new ProdutoController();
        ArrayList<ProdutoModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtProduto.getModel();
        modeloTabela.setRowCount(0);
        if(lista.isEmpty())
            JOptionPane.showMessageDialog(this, "Nenhum produto cadastrado!"
                    ,"Retorno Tela", JOptionPane.ERROR_MESSAGE);
        else{
            for(ProdutoModel p: lista){
                modeloTabela.addRow(new String[]{
                    String.valueOf(p.getIdproduto()),
                    p.getDescricao(),
                    String.valueOf(p.getEstoque()),
                    String.valueOf(p.getValor()),
                    String.valueOf(p.getFornecedor().getRazaoSocial())
                });
            }
        }
    }
    private void inicializa(){
        jtxidProduto.setEditable(true);
        jtxDescricao.setEditable(false);
        jtxEstoque.setEditable(false);
        jtxValor.setEditable(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }
    private void limparCampos(){
        jtxidProduto.setText("");
        jtxDescricao.setText("");
        jtxEstoque.setText("");
        jtxValor.setText("");
        jcbFornecedor.setSelectedIndex(0);
    }
    private void preencherCombo(){
        FornecedorController controller = new FornecedorController();
        listaFornecedores = controller.selecionarTodos();
        for(FornecedorModel f: listaFornecedores)
            jcbFornecedor.addItem(f.getRazaoSocial());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbFornecedor;
    private javax.swing.JTable jtProduto;
    private javax.swing.JTextField jtxDescricao;
    private javax.swing.JTextField jtxEstoque;
    private javax.swing.JTextField jtxValor;
    private javax.swing.JTextField jtxidProduto;
    // End of variables declaration//GEN-END:variables
}
